server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: movies_service
          uri: lb://movies-api
          predicates:
            - Path=/api/v1/movies/**
        - id: actors_service
          uri: lb://actors-api
          predicates:
            - Path=/api/v1/actors/**
