server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: movies_service
          uri: lb://movies-api
          predicates:
            - Path=/api/v1/movies/**
        - id: actors_service
          uri: lb://actors-api
          predicates:
            - Path=/api/v1/actors/**

custom:
  actor_details: http://actors-api/api/v1/actors/{id}
  movie_search: http://movies-api/api/v1/movies/search
